modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/FTB-Gamepedia/DefaultSkin/issues"
license="MIT"

[[mods]]
modId="defaultskin"
version="${mod_version}"
displayName="DefaultSkin"
displayURL="https://modrinth.com/mod/defaultskin"
credits=""
authors="SatanicSanta"
description="Adds a keybind to toggle between default and custom player skins."
displayTest="IGNORE_ALL_VERSION"

[[dependencies.defaultskin]]
    modId="neoforge"
    mandatory=true
    versionRange="[20.4,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.defaultskin]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.4,)"
    ordering="NONE"
    side="CLIENT"

[[mixins]]
    config="defaultskin_mixins.json"