modLoader="javafml"
loaderVersion="[25,)"
issueTrackerURL="https://github.com/FTB-Gamepedia/DefaultSkin/issues"
license="MIT"

[[mods]]
modId="defaultskin"
version="${file.jarVersion}"
displayName="DefaultSkin"
displayURL="https://modrinth.com/mod/defaultskin"
credits=""
authors="SatanicSanta"
description="Adds a keybind to toggle between default and custom player skins."
displayTest="IGNORE_ALL_VERSION"

[[dependencies.defaultskin]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.defaultskin]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17,1.17.1]"
    ordering="NONE"
    side="CLIENT"